name: Push Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Release
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        name: version
        id: version
      - run: zig build -Dversion=${{ env.VERSION }} -Doptimize=ReleaseSmall
        name: build
      - run: strip --strip-all ./zig-out/bin/vhttp
        name: strip
      - run: upx --best --lzma ./zig-out/bin/vhttp
        name: pack
      - run: zip -j vintus.http-${{ env.VERSION }}-linux-x86_64.zip ./zig-out/bin/vhttp
        name: zip
      - uses: softprops/action-gh-release@v2
        name: release
        with:
          files: |
            vintus.http-${{ env.VERSION }}-linux-x86_64.zip
